[package]
name = "ratatoist-nvim"
description = "Neovim plugin for Todoist (coming soon)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ratatoist-core = { path = "../ratatoist-core" }
